spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL

  jpa:
    database: h2
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

